### ISSUE TITLE
Software

### ISSUE THREAD

**Issue by mitchLui** [mitchLui/greenmap#2]
- [ ] Web App
  - [ ] Maps UI
  - [ ] Search
  - [ ] Display data (traffic, weather, availability)
- [ ] REST API
  - [ ] Voi + e-Bikes + Zipcar + Public transport support
  - [ ] Communication with Arduino

**Comment by mitchLui** [comment]
Voi API: https://github.com/ubahnverleih/WoBike/blob/master/Voi.md

Weather API: https://openweathermap.org/current

Transport API: https://developer.transportapi.com/docs?raml=https://docs.transportapi.com/raml/transportapi.raml

**Comment by artur-varosyan** [comment]
EV Charge Points (+ other transport data): https://developer.here.com/documentation/charging-stations/dev_guide/topics/overview.html

**Comment by artur-varosyan** [comment]
> EV Charge Points (+ other transport data): https://developer.here.com/documentation/charging-stations/dev_guide/topics/overview.html

This is not supported on the freemium plan

**Instead** we are going to use: https://openchargemap.org/site/develop/api#/
